// Constants for Documents
export const DOC_TYPES = {
	FETCH_DOCS: 'FETCH_DOCS',
	FETCH_DOC: 'FETCH_DOC',
	FETCH_MEMBERS: 'FETCH_MEMBERS',
	ADD_MEMBER: 'ADD_MEMBER',
	NEW_DOC: 'NEW_DOC',
	SAVE_DOC: 'SAVE_DOC',
	CHANGE_STATUS: 'CHANGE_STATUS',
}


// Constants for Users
export const USER_TYPES = {
	FETCH_USERS: 'FETCH_USERS',
	FETCH_USER: 'FETCH_USER',
	REGISTER_USER: 'REGISTER_USER',
	LOGIN_USER: 'LOGIN_USER',
	UPDATE_USER_ROLE: 'UPDATE_USER_ROLE',
	DELETE_USER: 'DELETE_USER'
};

export const TABOO_TYPES = {
	FETCH_TABOO: 'FETCH_TABOO'
}

export const HISTORY_TYPES = {
	FETCH_DOC_HIST: 'FETCH_DOC_HIST'
}